force-app/main/default/objects/Account/fields/Account_Activation_Summary__c.field-meta.xml
<CustomField>
    <fullName>Account_Activation_Summary__c</fullName>
    <description>Enter the account summary here</description>
    <label>Account Activation Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Help to check activeness of account</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ActivateAccountClass.cls
public with sharing class ActivateAccountClass {
    @AuraEnabled
    public static void activateAccount(Id recordId){
        try {
            Account acc = [SELECT Id, Active__c, Type, Account_Activation_Summary__c FROM Account WHERE Id = :recordId];
            if(acc.Type == 'Customer' && acc.Account_Activation_Summary__c != null){
                acc.Active__c = true;
                update acc;
            }
            else{
                throw new AuraHandledException('Either account type is not customer or summary is empty');
            }
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}