force-app/main/default/objects/Account/fields/Account_Activation_Summary__c.field-meta.xml
<CustomField>
    <fullName>Account_Activation_Summary__c</fullName>
    <description>Enter the account summary here</description>
    <label>Account Activation Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Help to check activeness of account</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Email__c.field-meta.xml
<CustomField>
    <fullName>Company_Email__c</fullName>
    <description>Company email field</description>
    <label>Company Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHelper.cls
public with sharing class AccountTriggerHelper {
    private static final String ACCOUNT_MANAGER_CP = 'Account_Manager_CP';
    private static final String CUSTOMER_TYPE = 'Customer';
    
    public static void checkAccountManagerPSAssignment(List<Account> accounts){
        if(! FeatureManagement.checkPermission(ACCOUNT_MANAGER_CP)){
            for(Account acc: accounts){
                acc.Active__c.addError(System.Label.AccountManagerLbl);
            }
        }
    }
    
    public static void doCreateContact(List<Account> accounts){
        Boolean defaultContactExist = checkDefaultContactExistence(accounts);
        List<Contact> contactWithAccounts = new List<Contact>();
        for(Account acc : accounts){
            if(acc.Type == CUSTOMER_TYPE && !defaultContactExist && acc.Active__c){
                if(acc.Account_Activation_Summary__c == null){
                    acc.addError(System.Label.AccountSummaryRequiredLbl); // check if summary is given if account is activated
                }
                else{
                    contactWithAccounts.add(new Contact(FirstName = acc.Name, LastName = 'Customer Representative', AccountId = acc.Id, Email = acc.Company_Email__c, Phone = acc.Phone));//Don't know what is custom representative
                }
                
            }
        }
        
        if(contactWithAccounts != null && !contactWithAccounts.isEmpty()){
            insert contactWithAccounts;
        }
    }
    
    private static Boolean checkDefaultContactExistence(List<Account> acc){
        return [SELECT Id FROM Contact WHERE AccountId IN :acc].size() > 0;
    }
}